// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TreMoc.Data;

#nullable disable

namespace TreMoc.Migrations
{
    [DbContext(typeof(TreMocDbContext))]
    [Migration("20260625120000_AddIsActiveToUser")]
    partial class AddIsActiveToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("TreMoc.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingProvince")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TreMoc.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("TreMoc.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImpactCo2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImpactPlastic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImpactWater")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Đồ gia dụng",
                            Description = "Khay trà tre tự nhiên, thiết kế tối giản, chế tác thủ công từ tre già 5 năm tuổi. Kích thước 30x20x3cm, phù hợp cho bàn trà gia đình.",
                            Image = "/images/bamboo_tea_tray.png",
                            ImagesJson = "[\"/images/bamboo_tea_tray.png\",\"/images/bamboo_cups.png\",\"/images/bamboo_organizer.png\"]",
                            ImpactCo2 = "25g",
                            ImpactPlastic = "50g",
                            ImpactWater = "100ml",
                            Name = "Khay Trà Tre",
                            Price = 280000m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 2,
                            Category = "Đồ gia dụng",
                            Description = "Bộ 4 cốc tre thủ công, mỗi chiếc đều là tác phẩm độc đáo. Dung tích 250ml, an toàn cho sức khỏe.",
                            Image = "/images/bamboo_cups.png",
                            ImagesJson = "[\"/images/bamboo_cups.png\",\"/images/bamboo_tea_tray.png\",\"/images/bamboo_cutting_board.png\"]",
                            ImpactCo2 = "40g",
                            ImpactPlastic = "80g",
                            ImpactWater = "200ml",
                            Name = "Bộ Cốc Tre",
                            Price = 195000m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 3,
                            Category = "Trang trí",
                            Description = "Hộp đựng bút và văn phòng phẩm từ tre, thiết kế gọn gàng nhiều ngăn, phù hợp bàn làm việc hiện đại.",
                            Image = "/images/bamboo_organizer.png",
                            ImagesJson = "[\"/images/bamboo_organizer.png\",\"/images/bamboo_lamp.png\",\"/images/bamboo_tea_tray.png\"]",
                            ImpactCo2 = "15g",
                            ImpactPlastic = "30g",
                            ImpactWater = "50ml",
                            Name = "Hộp Đựng Bút Tre",
                            Price = 150000m,
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = 4,
                            Category = "Trang trí",
                            Description = "Đèn trang trí đan từ tre thủ công, tạo ánh sáng ấm áp và không gian thư giãn. Đường kính 25cm.",
                            Image = "/images/bamboo_lamp.png",
                            ImagesJson = "[\"/images/bamboo_lamp.png\",\"/images/bamboo_organizer.png\",\"/images/bamboo_tea_tray.png\"]",
                            ImpactCo2 = "60g",
                            ImpactPlastic = "120g",
                            ImpactWater = "300ml",
                            Name = "Đèn Tre Trang Trí",
                            Price = 420000m,
                            StockQuantity = 1
                        },
                        new
                        {
                            Id = 5,
                            Category = "Nhà bếp",
                            Description = "Thớt tre dày 2cm, vân gỗ tự nhiên đẹp mắt, kháng khuẩn tự nhiên. Kích thước 35x25cm.",
                            Image = "/images/bamboo_cutting_board.png",
                            ImagesJson = "[\"/images/bamboo_cutting_board.png\",\"/images/bamboo_cups.png\",\"/images/bamboo_tea_tray.png\"]",
                            ImpactCo2 = "100g",
                            ImpactPlastic = "200g",
                            ImpactWater = "500ml",
                            Name = "Thớt Tre Cao Cấp",
                            Price = 220000m,
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 6,
                            Category = "Phòng tắm",
                            Description = "Bàn chải đánh răng từ tre tự nhiên, lông chải mềm mại, phân hủy sinh học 100%. Bộ 4 chiếc.",
                            Image = "/images/bamboo_toothbrush.png",
                            ImagesJson = "[\"/images/bamboo_toothbrush.png\",\"/images/bamboo_cups.png\",\"/images/bamboo_organizer.png\"]",
                            ImpactCo2 = "8g",
                            ImpactPlastic = "15g",
                            ImpactWater = "30ml",
                            Name = "Bàn Chải Tre",
                            Price = 45000m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 7,
                            Category = "Trang trí",
                            Description = "Giỏ tre đan thủ công hoa văn tinh xảo, dùng để trang trí hoặc đựng đồ. Đường kính 30cm.",
                            Image = "/images/bamboo_lamp.png",
                            ImagesJson = "[\"/images/bamboo_lamp.png\",\"/images/bamboo_organizer.png\",\"/images/bamboo_cups.png\"]",
                            ImpactCo2 = "45g",
                            ImpactPlastic = "90g",
                            ImpactWater = "150ml",
                            Name = "Giỏ Tre Đan",
                            Price = 350000m,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 8,
                            Category = "Nhà bếp",
                            Description = "Bộ 10 đôi đũa tre tự nhiên, đầu nhọn chống trượt, an toàn vệ sinh thực phẩm.",
                            Image = "/images/bamboo_cutting_board.png",
                            ImagesJson = "[\"/images/bamboo_cutting_board.png\",\"/images/bamboo_tea_tray.png\",\"/images/bamboo_cups.png\"]",
                            ImpactCo2 = "12g",
                            ImpactPlastic = "25g",
                            ImpactWater = "40ml",
                            Name = "Bộ Đũa Tre",
                            Price = 85000m,
                            StockQuantity = 20
                        });
                });

            modelBuilder.Entity("TreMoc.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TreMoc.Models.Order", b =>
                {
                    b.HasOne("TreMoc.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TreMoc.Models.OrderItem", b =>
                {
                    b.HasOne("TreMoc.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TreMoc.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TreMoc.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
